### ISSUE TITLE
Cancel button when editing project details from Dashboard

### ISSUE THREAD

**Issue by lrasmus** [StatTag/StatWrap#167] opened 2024-02-22 22:28 UTC
When the user is on the Dashboard tab for a project and clicks the "Edit Details" button, StatWrap opens up a way to modify the project details as well as the project tags.  The only available option is to "Save Details".  However, users should have a way to cancel any edits, and revert them.

1. Add a "Cancel" button to the right of the "Save Details" button
2. If the "Cancel" button is clicked, any edits should be discarded
3. After clicking "Cancel", the user should exit the editing interface and return to the view of the Dashboard

Ideally if the user had made changes, when they click "Cancel", step 2 should prompt the user "You have made changes.  Do you wish to discard those changes?"  This provides an extra protection if the user clicked Cancel by accident.

![image](https://github.com/StatTag/StatWrap/assets/967970/7a3688f7-e8e0-4d53-89a8-4fbbb133eb3a)

**Comment by Abhijay007** [comment] 2024-02-27 17:06
Hi @lrasmus, I opened PR #168 resolving issue #166, can I work on this issue now?

**Comment by Min2who** [comment] 2024-02-28 03:39
Hey @lrasmus can i work on this isssue

**Comment by Abhijay007** [comment] 2024-02-28 19:26
Hi @utnim2, it's great that you created a PR for solving this issue. It's a positive step for the betterment of the project. However, just a friendly reminder: it would be great if you could ask for an assignment from the project maintainer on the issue beforehand. If it's unassigned, please check if anyone else has commented to confirm whether they've started working on it or not, or if the issue is part of any milestone that has already been an ongoing effort by the team to resolve it.

If no one has requested an assignment, then only requesting an assignment is appropriate. By doing so, we can avoid duplicating efforts and ensure efficient use of resources. It's better to work on something else if an issue is already being addressed by someone else, as we already have a volunteer to address that issue. Please refrain from commenting unless the person who has assigned it becomes inactive on the issue. I hope you'll consider following good open-source practices for next time; this will help us to address more issues by different volunteers and help us to avoid spamming and reduce duplicate errors.

**Comment by utnim2** [comment] 2024-02-28 19:29
> Hi @utnim2, it's great that you created a PR for solving this issue. It's a positive step for the betterment of the project. However, just a friendly reminder: it would be great if you could ask for an assignment from the project maintainer on the issue beforehand. If it's unassigned, please check if anyone else has commented to confirm whether they've started working on it or not, or if the issue is part of any milestone that has already been an ongoing effort by the team to resolve it.
> 
> If no one has requested an assignment, then only requesting an assignment is appropriate. By doing so, we can avoid duplicating efforts and ensure efficient use of resources. It's better to work on something else if an issue is already being addressed by someone else, as we already have a volunteer to address that issue. Please refrain from commenting unless the person who has assigned it becomes inactive on the issue. I hope you'll consider following good open-source practices for next time; this will help us to address more issues by different volunteers and help us to avoid spamming and reduce duplicate errors.

I have talked to @lrasmus on slack

**Comment by Abhijay007** [comment] 2024-02-28 19:32
> > Hi @utnim2, it's great that you created a PR for solving this issue. It's a positive step for the betterment of the project. However, just a friendly reminder: it would be great if you could ask for an assignment from the project maintainer on the issue beforehand. If it's unassigned, please check if anyone else has commented to confirm whether they've started working on it or not, or if the issue is part of any milestone that has already been an ongoing effort by the team to resolve it.
> > If no one has requested an assignment, then only requesting an assignment is appropriate. By doing so, we can avoid duplicating efforts and ensure efficient use of resources. It's better to work on something else if an issue is already being addressed by someone else, as we already have a volunteer to address that issue. Please refrain from commenting unless the person who has assigned it becomes inactive on the issue. I hope you'll consider following good open-source practices for next time; this will help us to address more issues by different volunteers and help us to avoid spamming and reduce duplicate errors.
> 
> I have talked to @lrasmus on slack

sure thank you for bringing this to my attention. It wasn't mentioned previously, which is why I suggested it.

I believe it would be beneficial to create a contributing guide for the StatWrap repository, along with incorporating community links. This would enable other contributors to be informed about ongoing discussions and help prevent duplicated efforts.

cc : @lrasmus.

**Comment by lrasmus** [comment] 2024-02-28 20:53
Sorry for not responding quicker @Abhijay007 to your earlier inquiry!  Thank you @utnim2 for the contribution, I will review.  I will work on refining the contribution guide as well.

**Comment by Abhijay007** [comment] 2024-02-28 20:56
> Sorry for not responding quicker @Abhijay007 to your earlier inquiry! Thank you @utnim2 for the contribution, I will review. I will work on refining the contribution guide as well.

No Problem @lrasmus

**Comment by Abhijay007** [comment] 2024-02-28 21:03
> > Sorry for not responding quicker @Abhijay007 to your earlier inquiry! Thank you @utnim2 for the contribution, I will review. I will work on refining the contribution guide as well.
> 
> No Problem @lrasmus, let me know if you need any assistance in developing that contributing guide.

**Closed** 2024-06-18 03:00 UTC
Labels: good first issue
